-- ============================================================
-- Tabela de embalagens por pedido
-- ============================================================
CREATE TABLE public.pedido_embalagem (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id         bigint  NOT NULL REFERENCES public.pedido(id) ON DELETE CASCADE,
  embalagem_codprod bigint  REFERENCES public.embalagem(codprod),
  quantidade_caixas integer NOT NULL DEFAULT 1,
  peso_total        numeric NOT NULL DEFAULT 0,
  cenario           text    NOT NULL
    CHECK (cenario IN ('unitario', 'padrao', 'catalogo')),
  criado_em         timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.pedido_embalagem ENABLE ROW LEVEL SECURITY;
CREATE INDEX pedido_embalagem_pedido_id_idx ON public.pedido_embalagem (pedido_id);

-- ============================================================
-- Função de cálculo de embalagens
--
-- Regras:
--   unitario : qty = 1  → dimensões e peso do próprio produto
--   padrao   : produto tem codprodemb + qtdemb
--              → ceil(qty / qtdemb) caixas da embalagem padrão
--   catalogo : sem embalagem padrão
--              → menor caixa do catálogo que comporte volume total
--                em 1 caixa; se nenhuma couber, usa a maior e
--                calcula quantas caixas são necessárias
--
-- Peso total = (n_caixas × peso_embalagem) + (qty × peso_produto)
-- ============================================================
CREATE OR REPLACE FUNCTION public.calcular_embalagens_pedido(p_pedido_id bigint)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_item         RECORD;
  v_produto      RECORD;
  v_emb          RECORD;
  v_qtd_caixas   integer;
  v_peso_total   numeric;
  v_vol_total    numeric;
  v_vol_unitario numeric;
  v_cod_sel      bigint;
  v_vol_sel      numeric;
  v_peso_sel     numeric;
BEGIN
  DELETE FROM public.pedido_embalagem WHERE pedido_id = p_pedido_id;

  FOR v_item IN
    SELECT pi.quantidade, pi.codprod
    FROM public.pedido_item pi
    WHERE pi.pedido_id = p_pedido_id
  LOOP
    SELECT p.peso, p.altura, p.largura, p.comprimento, p.codprodemb, p.qtdemb
    INTO v_produto
    FROM public.produto p
    WHERE p.codprod = v_item.codprod;

    IF NOT FOUND THEN CONTINUE; END IF;

    -- CENÁRIO 1: 1 unidade — peso e medidas do produto unitário
    IF v_item.quantidade = 1 THEN
      INSERT INTO public.pedido_embalagem
        (pedido_id, embalagem_codprod, quantidade_caixas, peso_total, cenario)
      VALUES
        (p_pedido_id, NULL, 1, COALESCE(v_produto.peso, 0), 'unitario');
      CONTINUE;
    END IF;

    -- CENÁRIO 2: embalagem coletiva padrão definida no produto
    IF v_produto.codprodemb IS NOT NULL AND COALESCE(v_produto.qtdemb, 0) > 0 THEN
      v_qtd_caixas := CEIL(v_item.quantidade / v_produto.qtdemb::numeric)::integer;

      SELECT e.peso INTO v_emb
      FROM public.embalagem e
      WHERE e.codprod = v_produto.codprodemb;

      v_peso_total := v_qtd_caixas * COALESCE(v_emb.peso, 0)
                    + v_item.quantidade * COALESCE(v_produto.peso, 0);

      INSERT INTO public.pedido_embalagem
        (pedido_id, embalagem_codprod, quantidade_caixas, peso_total, cenario)
      VALUES
        (p_pedido_id, v_produto.codprodemb, v_qtd_caixas, v_peso_total, 'padrao');
      CONTINUE;
    END IF;

    -- CENÁRIO 3: catálogo fixo
    -- Itera ASC por volume; guarda sempre o candidato atual (= maior ao fim do loop)
    -- e sai na primeira caixa que comporte o volume total em 1 box
    IF COALESCE(v_produto.altura, 0) > 0
       AND COALESCE(v_produto.largura, 0) > 0
       AND COALESCE(v_produto.comprimento, 0) > 0
    THEN
      v_vol_unitario := v_produto.altura * v_produto.largura * v_produto.comprimento;
      v_vol_total    := v_item.quantidade * v_vol_unitario;

      v_cod_sel  := NULL;
      v_vol_sel  := NULL;
      v_peso_sel := NULL;

      FOR v_emb IN
        SELECT e.codprod,
               e.peso,
               (e.altura * e.largura * e.comprimento) AS volume
        FROM public.embalagem e
        WHERE e.altura IS NOT NULL AND e.largura IS NOT NULL AND e.comprimento IS NOT NULL
          AND e.altura > 0 AND e.largura > 0 AND e.comprimento > 0
        ORDER BY (e.altura * e.largura * e.comprimento) ASC
      LOOP
        v_cod_sel  := v_emb.codprod;
        v_vol_sel  := v_emb.volume;
        v_peso_sel := v_emb.peso;
        EXIT WHEN v_emb.volume >= v_vol_total;
      END LOOP;

      IF v_cod_sel IS NOT NULL THEN
        v_qtd_caixas := CEIL(v_vol_total / v_vol_sel)::integer;
        v_peso_total := v_qtd_caixas * COALESCE(v_peso_sel, 0)
                      + v_item.quantidade * COALESCE(v_produto.peso, 0);

        INSERT INTO public.pedido_embalagem
          (pedido_id, embalagem_codprod, quantidade_caixas, peso_total, cenario)
        VALUES
          (p_pedido_id, v_cod_sel, v_qtd_caixas, v_peso_total, 'catalogo');
      ELSE
        INSERT INTO public.pedido_embalagem
          (pedido_id, embalagem_codprod, quantidade_caixas, peso_total, cenario)
        VALUES
          (p_pedido_id, NULL, 1, v_item.quantidade * COALESCE(v_produto.peso, 0), 'unitario');
      END IF;

    ELSE
      INSERT INTO public.pedido_embalagem
        (pedido_id, embalagem_codprod, quantidade_caixas, peso_total, cenario)
      VALUES
        (p_pedido_id, NULL, 1, v_item.quantidade * COALESCE(v_produto.peso, 0), 'unitario');
    END IF;

  END LOOP;
END;
$$;

-- ============================================================
-- Trigger: recalcula embalagens em tempo real via pedido_item
-- Dispara em INSERT, UPDATE (quando qty/produto muda) e DELETE
-- As embalagens ficam prontas antes do pagamento para cálculo de frete
-- ============================================================
CREATE OR REPLACE FUNCTION public.trg_fn_embalagem_pedido_item()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_pedido_id bigint;
BEGIN
  v_pedido_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.pedido_id ELSE NEW.pedido_id END;

  -- Ignora UPDATE sem alteração de quantidade ou produto
  IF TG_OP = 'UPDATE'
     AND NEW.quantidade = OLD.quantidade
     AND NEW.codprod    = OLD.codprod
  THEN
    RETURN NEW;
  END IF;

  IF v_pedido_id IS NOT NULL THEN
    PERFORM public.calcular_embalagens_pedido(v_pedido_id);
  END IF;

  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

CREATE TRIGGER tr_pedido_item_embalagem
  AFTER INSERT OR UPDATE OR DELETE ON public.pedido_item
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_fn_embalagem_pedido_item();
